// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Conference.Models
{
    [Table("Event")]
    public partial class Event
    {
        public Event()
        {
            EventActivity_Singles = new HashSet<EventActivity_Single>();
            EventSubscriptions = new HashSet<EventSubscription>();
        }

        [Key]
        public int EventId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventDate { get; set; }
        public string EventLocation { get; set; }
        [StringLength(50)]
        public string EventBarcode { get; set; }
        public bool EventIsActive { get; set; }
        public string EventTitle { get; set; }
        public string QRCodeName { get; set; }
        public string EventVideo { get; set; }
        public string QRCodeImage { get; set; }
        public string IndividualImage { get; set; }
        public string AudianceImage { get; set; }
        public string QueueImage { get; set; }

        [InverseProperty("Event")]
        public virtual ICollection<EventActivity_Single> EventActivity_Singles { get; set; }
        [InverseProperty("Event")]
        public virtual ICollection<EventSubscription> EventSubscriptions { get; set; }
    }
}