// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Conference.Models
{
    [Table("EventSubscription")]
    public partial class EventSubscription
    {
        public EventSubscription()
        {
            SubscriptionActivities = new HashSet<SubscriptionActivity>();
        }

        [Key]
        public int EventSubscriptionId { get; set; }
        public int EventId { get; set; }
        public int? EventSubscriptionType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EventSubscriptionDate { get; set; }
        public int? EventSubscriptionQueue { get; set; }
        public string EventSubscriptionFullName { get; set; }
        public string EventSubscriptionMobile { get; set; }

        [ForeignKey("EventId")]
        [InverseProperty("EventSubscriptions")]
        public virtual Event Event { get; set; }
        [InverseProperty("EventSubscription")]
        public virtual ICollection<SubscriptionActivity> SubscriptionActivities { get; set; }
    }
}